Ka add schools to picker
International-Mentorship-ISMP/ismp pull request #495
Opened 2020-12-31 00:44 UTC by kailanjian

## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 

## Types of changes

- [ ] I've labeled this PR with appropriate labels (`comp/*` component, bug/feature, documentation and other less important ones).

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [ ] I've linked the proper todo
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests (unit, integration...etc.) that prove my fix is effective or that my change works
- [ ] I have added or updated necessary documentation (if appropriate). You can search, for instance using the [`silver searcher`](https://github.com/ggreer/the_silver_searcher) `ag <STRING>` to find all usages in the repository.
- [ ] I have notified the team of any breaking or important changes

2021-01-02 00:04 UTC, richyen requested changes
otherwise looks ok

2021-01-02 00:04 UTC, richyen commented on frontend/src/pages/ApplicationForm/ApplicationForm.jsx
> +        handlppliceFeedbackChange(fieldName, 'validations.check_terms');
is this a typo?

2021-01-03 08:13 UTC, richyen commented on frontend/src/utils/data_files/sorted_schools_list.js
> +
For the record, if we ever want *all* schools, I think we'd pull from here:
https://ope.ed.gov/dapip/#/download-data-files

2021-01-05 05:38 UTC, kailanjian commented on frontend/src/pages/ApplicationForm/ApplicationForm.jsx
> +        handlppliceFeedbackChange(fieldName, 'validations.check_terms');
@richyen this is fixed!

2021-01-05 05:40 UTC, kailanjian commented on frontend/src/utils/data_files/sorted_schools_list.js
> +
I used Dustin's file that has mappings to regions, other schools wouldn't be auto-mapped anyway so it's ok if people type them in, but maybe we can do that as the need arises

2021-01-05 08:26 UTC, merged